# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
- linux

# Use Travis' container-based architecture
sudo: false

env:
  global:
  # The following versions are the 'default' for tests, unless
  # overidden underneath. They are defined here in order to save having
  # to repeat them for all configurations.
  - PYTHON_VERSION=3.7
  - PIP_DEPENDENCIES='tox'
  - RUN_CMD='pytest'

  matrix:
  - PYTHON_VERSION=3.5
  - PYTHON_VERSION=3.6
  - PYTHON_VERSION=3.7

matrix:
  fast_finish: true
  include:

  - env: PIP_DEPENDENCIES='tox twine' TWINE_CHECK=1

  # Try a run on OSX
  - os: osx
    env: PYTHON_VERSION=3.7

  # Run a series of tests on Windows
  - os: windows
    env: PYTHON_VERSION=3.5

  - os: windows
    env: PYTHON_VERSION=3.6

  - os: windows
    env: PYTHON_VERSION=3.7

install:
- git clone git://github.com/astropy/ci-helpers.git
- source ci-helpers/travis/setup_conda.sh
- pip install .

script:
- if [[ $TWINE_CHECK ]]; then
  python setup.py build sdist;
  twine check dist/*;
  else
  $RUN_CMD;
  fi
